--- 
Administrator: 
  authentication: 
    type: nick
    nicks: 
       - imajes
       - wiredfool
       - buridan
       - kevinmarks
       - joiito
  class: Administrator
  command_prefix: %
Insulter: 
  class: Insulter
  command_prefix: "?"
Heralder:
  class: Heralder
  command_prefix: "?"
Karma:
  class: Karma
  command_prefix: "?"
NyTimes:
  class: NyTimes
  command_prefix: "?"
