--- 
Administrator: 
  authentication: 
    type: nick
    nicks: 
       - imajes
       - wiredfool
       - buridan
       - kevinmarks
       - joiito
       - cskaterun
  class: Administrator
Insulter: 
  class: Insulter
Heralder:
  class: Heralder
Karma:
  class: Karma
