--- 
Freenode: 
  server: chat.freenode.net
  nick: jibot-testing
  leaves: 
  - Karma
  - Administrator
  - Heralder
  - Insulter
  - NYTimes
  rejoin: true
  channels:
    - "#joiito"
    - "#jibot"
  # bots:
  #   - jibot
  #   - jibot2
  #   - phenny
  #   - xena
  #   - datum
  #   - shorten
  #   - workbench
  #   - surly
  #   - chomp
