--- 
Freenode: 
  server: chat.freenode.net
  nick: jibot
  leaves: 
  - Karma
  - Administrator
  - Heralder
  - Insulter
  rejoin: true
  channels:
    - "#joiito"
    - "#jibot"
    - "#freeculture"
  #  - "#technorati"
    - "#jeanniecool"
    - "#suwcharman"
  #  - "#icann"
   # - "#microformats"
    - "#webkit"
    - "#chromium"
   # - "#barcamp"
   # - "#aoir_general"
   # - "#shdh"
    - "#jhuacm"
   # - "#openid"
  # bots:
  #   - jibot
  #   - jibot2
  #   - phenny
  #   - xena
  #   - datum
  #   - shorten
  #   - workbench
  #   - surly
  #   - chomp
GimpNet:
  server: irc.neitzert.com
  nick: jibot
  leaves: 
  - Karma
  - Administrator
  - Heralder
  - Insulter
  rejoin: true
  channels:
    - "#dnalounge"