--- 
Freenode: 
  server: chat.freenode.net
  nick: jibot2
  leaves: 
  - Karma
  - Administrator
  - Heralder
  - Insulter
  rejoin: true
  channels:
    - "#joiito"
    - "#jibot"
    - "#freeculture"
    - "#technorati"
    - "#jeanniecool"
    - "#suwcharman"
    - "#icann"
    - "#microformats"
    - "#webkit"
    - "#barcamp"
    - "#aoir_general"
    - "#shdh"
    - "#jhuacm"
    - "#openid"
  
